### ISSUE TITLE
key errors from bloom release

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/bloom#356]
See: https://github.com/ros/rosdistro/pull/7038

These are the errors:

```
Pre-verifying Debian dependency keys...
[info] Running 'rosdep update'...
[debug] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bloom/generators/common.py", line 119, in resolve_rosdep_key
    return resolve_for_os(key, view, installer, os_name, os_version)
  File "/usr/lib/python2.7/dist-packages/rosdep2/catkin_support.py", line 81, in resolve_for_os
    d = view.lookup(rosdep_key)
  File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 187, in lookup
    return self.rosdep_defs[rosdep_name]
KeyError: 'epos_library'
 
[debug] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bloom/generators/common.py", line 119, in resolve_rosdep_key
    return resolve_for_os(key, view, installer, os_name, os_version)
  File "/usr/lib/python2.7/dist-packages/rosdep2/catkin_support.py", line 81, in resolve_for_os
    d = view.lookup(rosdep_key)
  File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 187, in lookup
    return self.rosdep_defs[rosdep_name]
KeyError: 'epos_library'
 
[debug] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bloom/generators/common.py", line 119, in resolve_rosdep_key
    return resolve_for_os(key, view, installer, os_name, os_version)
  File "/usr/lib/python2.7/dist-packages/rosdep2/catkin_support.py", line 81, in resolve_for_os
    d = view.lookup(rosdep_key)
  File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 187, in lookup
    return self.rosdep_defs[rosdep_name]
KeyError: 'epos_library'
 
[debug] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bloom/generators/common.py", line 119, in resolve_rosdep_key
    return resolve_for_os(key, view, installer, os_name, os_version)
  File "/usr/lib/python2.7/dist-packages/rosdep2/catkin_support.py", line 81, in resolve_for_os
    d = view.lookup(rosdep_key)
  File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 187, in lookup
    return self.rosdep_defs[rosdep_name]
KeyError: 'epos_library'
 
[info] All keys are OK
```

**Comment by wjwwood** [comment]
Actually, after deeper introspection, these are expected tracebacks, they are later caught and then it falls back to the peer packages, which `epos_library` is in this case to `epos_hardware`.

**Comment by wjwwood** [comment]
The original issue was a mixup of the source and release repository urls.
