### ISSUE TITLE
Bloom requires working directory to be git repository

### ISSUE THREAD

**Issue by kmhallen** [ros-infrastructure/bloom#359]
When releasing a new version of a package, it shouldn't be necessary for the working directory to be a git repository. I ended up using 'git init' in a temporary folder, and then the release process succeeded.

    kevin@ubuntu:~$ bloom-release ueye --track jade --rosdistro jade
    Traceback (most recent call last):
      File "/usr/bin/bloom-release", line 9, in <module>
        load_entry_point('bloom==0.5.17', 'console_scripts', 'bloom-release')()
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1302, in main
        args.override_release_repository_push_url)
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1151, in perform_release
        from bloom.commands.git.config import convert_old_bloom_conf
      File "/usr/lib/python2.7/dist-packages/bloom/commands/git/__init__.py", line 5, in <module>
        upconvert_bloom_to_config_branch()
      File "/usr/lib/python2.7/dist-packages/bloom/config.py", line 296, in upconvert_bloom_to_config_branch
        check_for_multiple_remotes()
      File "/usr/lib/python2.7/dist-packages/bloom/config.py", line 280, in check_for_multiple_remotes
        remotes = get_remotes()
      File "/usr/lib/python2.7/dist-packages/bloom/git.py", line 741, in get_remotes
        raise RuntimeError("Directory '{0}' is not in a git repository.".format(checked_dir))
    RuntimeError: Directory '/home/kevin' is not in a git repository.

**Comment by wjwwood** [comment]
Sorry about that, fixed in 548f97f, I'm releasing 0.5.18 now.

**Comment by wjwwood** [comment]
`0.5.18` is out now, @tfoote Can you do the ftp sync?

**Comment by tfoote** [comment]
pushed

**Comment by k-okada** [comment]
could you push this to shadow-fixed too?

**Comment by tfoote** [comment]
shadow fixed sync automatically each time a rebuild completes. It should be there relatively soon.

**Comment by k-okada** [comment]
thanks, it was updated

--
◉ Kei Okada
