### ISSUE TITLE
Random bloom failure when github unreachable

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/bloom#377]
Saw this today; probably just a transient failure due to wifi or github flakiness, but it would be nice if it retried:

```
==> git-bloom-generate -y rosrpm --prefix release/indigo indigo -i 0
Traceback (most recent call last):
  File "/usr/bin/git-bloom-generate", line 9, in <module>
    load_entry_point('bloom==0.5.20', 'console_scripts', 'git-bloom-generate')()
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/generate.py", line 252, in main
    run_generator(generator, args)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/generate.py", line 120, in run_generator
    gen.handle_arguments, arguments)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/generate.py", line 101, in try_execute
    retcode = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bloom/generators/rosrpm.py", line 62, in handle_arguments
    ret = RpmGenerator.handle_arguments(self, args)
  File "/usr/lib/python2.7/dist-packages/bloom/generators/rpm/generator.py", line 441, in handle_arguments
    index = rosdistro.get_index(rosdistro.get_index_url())
  File "/usr/lib/python2.7/dist-packages/rosdistro/__init__.py", line 113, in get_index
    yaml_str = load_url(url)
  File "/usr/lib/python2.7/dist-packages/rosdistro/loader.py", line 59, in load_url
    raise URLError(str(e) + ' (%s)' % url)
URLError: <urlopen error <urlopen error [Errno -2] Name or service not known> (https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml)>

<== Error running command '['/usr/bin/git-bloom-generate', '-y', 'rosrpm', '--prefix', 'release/indigo', 'indigo', '-i', '0']'
Release failed, exiting.
```

The URL in question works fine 30 seconds after this error, and a second run of bloom succeeded.

**Comment by wjwwood** [comment]
I'm not sure bloom should try to catch all net failures and retry. But I'll take a pr that improves the situation if you're motivated to do so.
