### ISSUE TITLE
bloom-release behind proxy fails to resolve hostname

### ISSUE THREAD

**Issue by NikolausDemmel** [ros-infrastructure/bloom#388]
I'm sitting behind a proxy (I have `http_proxy` and `https_proxy` set correctly) and want to run bloom-release to release a package for the first time, but it fails:
```
$ bloom-release --rosdistro indigo --track indigo foobar_msgs --edit
Traceback (most recent call last):
  File "/usr/bin/bloom-release", line 9, in <module>
    load_entry_point('bloom==0.5.21', 'console_scripts', 'bloom-release')()
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1316, in main
    args.override_release_repository_push_url)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1168, in perform_release
    release_repo = get_release_repo(repository, distro, override_release_repository_url)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 358, in get_release_repo
    url = get_repo_uri(repository, distro)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 306, in get_repo_uri
    distribution_file = get_distribution_file(distro)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 255, in get_distribution_file
    files = rosdistro.get_distribution_files(get_index(), distro)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 216, in get_index
    _rosdistro_index = rosdistro.get_index(get_index_url())
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 191, in get_index_url
    data = gh.get_branch(owner, repo, branch)
  File "/usr/lib/python2.7/dist-packages/bloom/github.py", line 142, in get_branch
    resp = do_github_get_req(url, auth=self.auth)
  File "/usr/lib/python2.7/dist-packages/bloom/github.py", line 73, in do_github_get_req
    conn.request('GET', path, '', headers)
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1178, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -5] No address associated with hostname
```

**Comment by wjwwood** [comment]
Hmm, I never tested behind a proxy. I'm not sure how to fix it, and I don't have time at the moment to pursue a fix. I'll mark it as "untargeted" for now. Please let me know if you have a fix.

**Comment by NikolausDemmel** [comment]
I can reproduce this by manually calling `getaddrinfo('api.github.com', 80, 0, SOCK_STREAM)`, but haven't investigated further. I don't have a fix for now. I ran what I needed from a machine with direct internet access.
