### ISSUE TITLE
git-bloom-patch export May Fail due to Ambiguous SHA Hash

### ISSUE THREAD

**Issue by evenator** [ros-infrastructure/bloom#392]
If there is more than one commit with the same first 7 digits of the SHA hash, bloom fails.

```
 [git-bloom-patch export]: 'execute_command' failed to call 'git format-patch -M -B 2888c70...debian/jade/utopic/swri_route_util' which had a return code (128):
 [git-bloom-patch export]: ```
error: short SHA1 2888c70 is ambiguous.
fatal: ambiguous argument '2888c70...debian/jade/utopic/swri_route_util': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

 [git-bloom-patch export]: ```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/generate.py", line 101, in try_execute
    retcode = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bloom/logging.py", line 211, in decorated
    return f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/patch/export_cmd.py", line 53, in export_patches
    execute_command(cmd, cwd=directory)
  File "/usr/lib/python2.7/dist-packages/bloom/util.py", line 461, in execute_command
    raise CalledProcessError(result, cmd)
CalledProcessError: Command 'git format-patch -M -B 2888c70...debian/jade/utopic/swri_route_util' returned non-zero exit status 128

Error calling git-bloom-patch export: Command 'git format-patch -M -B 2888c70...debian/jade/utopic/swri_route_util' returned non-zero exit status 128
git-bloom-patch export returned exit code (128)
```

**Comment by evenator** [comment]
Bloom log: https://gist.github.com/evenator/e4b8b009f79ff382b79cce22228cdf07

**Comment by evenator** [comment]
I was able to work around this by manually checking out the patches branch and committing an unambiguous hash (see https://github.com/swri-robotics-gbp/marti_common-release/commit/d776f0be5396cef0013a57e9ebb152db4b3bd761).

I think it would be prudent to use full hashes in bloom to avoid ambiguities like this.

**Comment by wjwwood** [comment]
Sorry for the issues it caused you. I'll try to implement this next time I spend time on bloom, but that might be a while.

**Comment by evenator** [comment]
It's about a 1 in 268 million bug. Figures that it hits me on Friday 13.
