### ISSUE TITLE
ascii encoding error when importing upstream

### ISSUE THREAD

**Issue by asmodehn** [ros-infrastructure/bloom#410]
I am trying to make a third party release of : https://github.com/django/django/tree/stable/1.8.x
with : 
```
alexv@asmodehn:~/Projects/catkin_ws$ bloom-release  --version
0.5.23
```
I get this error : 
```
Executing release track 'indigo'
==> bloom-export-upstream https://github.com/django/django.git git --tag 1.8.7 --display-uri https://github.com/django/django.git --name upstream --output-dir /tmp/tmp_WEGL0
Checking out repository at 'https://github.com/django/django.git' to reference '1.8.7'.
Cloning into '/tmp/6IdEBv/upstream'...
remote: Counting objects: 371868, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 371868 (delta 20), reused 0 (delta 0), pack-reused 371808
Receiving objects: 100% (371868/371868), 147.82 MiB | 2.28 MiB/s, done.
Resolving deltas: 100% (269218/269218), done.
Checking connectivity... done.
Exporting to archive: '/tmp/tmp_WEGL0/upstream-1.8.7.tar.gz'
warning: --depth is ignored in local clones; use file:// instead.
Cloning into '/tmp/tmpli8_ZY'...
done.
Note: checking out '8dd33d429892fc06cc9aa655012491f029f5f491'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Traceback (most recent call last):
  File "/usr/bin/bloom-export-upstream", line 9, in <module>
    load_entry_point('bloom==0.5.23', 'console_scripts', 'bloom-export-upstream')()
  File "/usr/lib/python2.7/dist-packages/bloom/commands/export_upstream.py", line 159, in main
    args.display_uri, args.name)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/export_upstream.py", line 136, in export_upstream
    if not upstream_repo.export_repository(tag or '', tarball_path):
  File "/usr/lib/python2.7/dist-packages/vcstools/git.py", line 752, in export_repository
    archiver.create(filepath)
  File "/usr/lib/python2.7/dist-packages/vcstools/git_archive_all.py", line 166, in create
    self.archive_all_files(archiver)  # this will take care of submodule init and update
  File "/usr/lib/python2.7/dist-packages/vcstools/git_archive_all.py", line 281, in archive_all_files
    for file_path in self.walk_git_files():
  File "/usr/lib/python2.7/dist-packages/vcstools/git_archive_all.py", line 314, in walk_git_files
    not path.islink(main_repo_file_path) and path.isdir(main_repo_file_path)
  File "/usr/lib/python2.7/posixpath.py", line 142, in islink
    st = os.lstat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2297' in position 46: ordinal not in range(128)

<== Error running command '['/usr/bin/bloom-export-upstream', 'https://github.com/django/django.git', 'git', '--tag', '1.8.7', '--display-uri', 'https://github.com/django/django.git', '--name', 'upstream', '--output-dir', '/tmp/tmp_WEGL0']'
Release failed, exiting.
```

I haven't dived into this issue yet, but I was able to reproduce it 2 times in a row.

**Comment by v-lopez** [comment]
Happening to me too, trying to release a package that contains files or directories with non-ASCII characters.

Probably introduced here: https://github.com/ros-infrastructure/bloom/blob/master/bloom/util.py#L363

If you change the variable to "en_US.UTF-8" it solves the ASCII thing, and to the best of my knowledge, should force the English language too.

**Comment by facontidavide** [comment]
I am having the same problem :(

**Comment by nuclearsandwich** [comment]
@asmodehn we made a lot of UTF-8 handling improvements to bloom and catkin_pkg around bloom 0.6.0 (#432).

I ran just the command

```
mkdir /tmp/bloom_django && bloom-export-upstream https://github.com/django/django.git \
git --tag 1.8.7 --display-uri https://github.com/django/django.git --name upstream \
--output-dir /tmp/bloom_django
```

And it completed without error. I am going to close the issue under the impression it's been resolved but if you perform a more complete test and there are still problems please feel free to re-open it. Thanks.
