### ISSUE TITLE
Failed to open pull request: AttributeError - 'GithubException' object has no attribute 'resp'

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/bloom#448]
```
$ bloom-release --rosdistro kinetic --track kinetic geometric_shapes -p
:
       url: https://github.com/ros-planning/geometric_shapes.git

Looks like bloom doesn't have an oauth token for you yet.
Therefore bloom will require your GitHub username and password just this once.
With your GitHub username and password bloom will create an oauth token on your behalf.
The token will be stored in `~/.config/bloom`.
You can delete the token from that file to have a new token generated.
Guard this token like a password, because it allows someone/something to act on your behalf.
If you need to unauthorize it, remove it from the 'Applications' menu in your GitHub account page.

Would you like to create an OAuth token now [Y/n]? 
GitHub username [n130s]: 130s
GitHub password (never stored): 
HTTP Error 401: Unauthorized (https://api.github.com/authorizations): None

Failed to open pull request: AttributeError - 'GithubException' object has no attribute 'resp'

$ ll ~/.config/bloom
ls: cannot access '/home/n130s/.config/bloom': No such file or directory

$ tail -n 25 ~/.bloom_logs/bloom-release_2017-11-26_16.35.06.885019.log
[info]      source:
[info]        type: git
[info]        url: https://github.com/ros-planning/geometric_shapes.git
[info] 
[warning] Looks like bloom doesn't have an oauth token for you yet.
[warning] Therefore bloom will require your GitHub username and password just this once.
[warning] With your GitHub username and password bloom will create an oauth token on your behalf.
[warning] The token will be stored in `~/.config/bloom`.
[warning] You can delete the token from that file to have a new token generated.
[warning] Guard this token like a password, because it allows someone/something to act on your behalf.
[warning] If you need to unauthorize it, remove it from the 'Applications' menu in your GitHub account page.
[info] 
[error] HTTP Error 401: Unauthorized (https://api.github.com/authorizations): None
[info] 
[debug] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1239, in perform_release
    track, repository, distro, interactive, override_release_repository_url
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 768, in open_pull_request
    gh = get_github_interface()
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 692, in get_github_interface
    if '{0}'.format(exc.resp.status) in ['401']:
AttributeError: 'GithubException' object has no attribute 'resp'

[error] Failed to open pull request: AttributeError - 'GithubException' object has no attribute 'resp'
[error] SYS.EXIT

$ apt-cache policy python-bloom
python-bloom:
  Installed: 0.6.1-1
  Candidate: 0.6.1-1
  Version table:
 *** 0.6.1-1 500
        500 http://packages.ros.org/ros/ubuntu xenial/main amd64 Packages
        500 http://packages.ros.org/ros/ubuntu xenial/main i386 Packages
        100 /var/lib/dpkg/status
```
I confirmed the GitHub password is correct.
I don't see anything that seems related to `bloom` on https://github.com/settings/applications

**Comment by nuclearsandwich** [comment]
It looks like Bloom isn't handling the case where a GitHubException object has no `resp` attribute. https://github.com/ros-infrastructure/bloom/blob/4ae25bb5d0a61b09cf007cad071455c2efe53c8b/bloom/github.py#L108-L109

**Comment by 130s** [comment]
@nuclearsandwich are you aware of any plan to fix this sometime this week? If not I hope I can give it a try (this blocks me making the release of MoveIt! https://github.com/ros-planning/moveit/issues/686#issuecomment-347055265).

**Comment by nuclearsandwich** [comment]
I'm going to take a look at it this morning. I haven't tried to reproduce the issue locally yet and I have some concerns that fixing the exposed bug may not resolve whatever API change caused the exception to occur in the first place. If I haven't gotten a PR together with a fix by the end of the day I'd suggest not waiting as I am trying to get some other tasks wrapped up on a deadline. I'll share what I've learned when I reach my time limit for the week and you can decide whether to pick up where I left of with a fix or creating the release PR manually based on your own requirements. Thanks!

**Comment by nuclearsandwich** [comment]
@130s do you have 2FA enabled? I've reproduced the issue and I'm pretty sure that the path should lead to a warning that users with 2FA enabled will need to generate and set their own token.

If you populate `~/.config/bloom` with `{ "username": "130s", "oauth_token": "YOUR OAUTH TOKEN"}` are you able to proceed?

**Comment by nuclearsandwich** [comment]
Okay, near as I can tell here's what's happening:

Bloom's token generation functions explicitly check the return code and assume that 401 means that 2FA is enabled and rather than handling the auth flow, bloom should suggest the user generate a token and place it in a hand-made bloom config.  That code is here:

https://github.com/ros-infrastructure/bloom/blob/c40ab07609e199b13c4088cdb03f9c1071c4f900/bloom/github.py#L119-L137

But on line 128 above, the 401 is generating an `HTTPError` within that function, which is being caught and re-raised as a `GitHubException` with no `resp` (lines 94-95 below).

https://github.com/ros-infrastructure/bloom/blob/c40ab07609e199b13c4088cdb03f9c1071c4f900/bloom/github.py#L84-L99

To mitigate this the 2FA handling logic needs to be shuffled around to handle the `GitHubException` from `do_github_post_req`

@130s I'm not likely to get a fix out this week, but whether you have 2FA enabled or not, placing your own bloom config file should allow you to circumvent this and allow bloom to generate your PR.

**Comment by 130s** [comment]
@nuclearsandwich Thank you for digging into this!

> do you have 2FA enabled? I've reproduced the issue and I'm pretty sure that the path should lead to a warning that users with 2FA enabled will need to generate and set their own token.
>
> If you populate ~/.config/bloom with { "username": "130s", "oauth_token": "YOUR OAUTH TOKEN"} are you able to proceed?

Yes, and by adding the `~/.config/bloom` file back, I see bloom works (`"username"` must be `"github_user"` ;)) as in the [wiki](http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization#Token-based_authentication). My issue resolved.

So, I agree that permanent fix is needed as the error message isn't helpful.

**Comment by nuclearsandwich** [comment]
> "username" must be "github_user" ;)) as in the wiki.

whoop. Good catch, I'll edit my initial post so as not to confuse people browsing.

**Comment by nuclearsandwich** [comment]
@130s out of curiosity what python version are you running bloom for.

**Comment by 130s** [comment]
```
$ python -V
Python 2.7.12
```

**Comment by nuclearsandwich** [comment]
https://github.com/ros-infrastructure/bloom/pull/451 is an attempt to improve the error handling in this case. Since those of us with multi-factor auth enabled cannot use the automatic token creation anyway, this just fixes the explanation for us when no token is present.
