### ISSUE TITLE
Can't release git repos with files with spaces in their names in the root dir

### ISSUE THREAD

**Issue by pjreed** [ros-infrastructure/bloom#450]
I've got a repository I'm trying to release that has a file in the root folder with spaces in its name.  `bloom-release` fails at the `git-bloom-generate` step, apparently because it executes "git rm -rf" on all of the files in the root dir without escaping their names.  Example output:

```bash
==> git-bloom-generate -y rosrelease kinetic --source upstream -i 0
Releasing packages: ['velocity_aggregation', 'imu_processing', 'marti_localization_msgs', 'gps_processing', 'localization_calibration_tools', 'marti_state_estimator', 'wheel_encoder_processing', 'localization_util', 'nmea_writer']
Releasing package 'velocity_aggregation' for 'kinetic' to: 'release/kinetic/velocity_aggregation'
 [git-bloom-patch trim]: 'execute_command' failed to call 'git rm -rf marti_state_estimator imu_processing README.md gps_processing velocity_aggregation Localization Data Flow.png marti_localization_msgs localization_util localization_calibration_tools wheel_encoder_processing nmea_writer' which had a return code (128):
 [git-bloom-patch trim]: ```
fatal: pathspec 'Localization' did not match any files

 [git-bloom-patch trim]: ```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/generate.py", line 101, in try_execute
    retcode = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bloom/generators/release.py", line 129, in post_rebase
    return trim(trim_d)
  File "/usr/lib/python2.7/dist-packages/bloom/logging.py", line 211, in decorated
    return f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/patch/trim_cmd.py", line 177, in trim
    new_config = _trim(new_config, force, directory)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/patch/trim_cmd.py", line 107, in _trim
    execute_command('git rm -rf ' + ' '.join(items), cwd=directory)
  File "/usr/lib/python2.7/dist-packages/bloom/util.py", line 461, in execute_command
    raise CalledProcessError(result, cmd)
CalledProcessError: Command 'git rm -rf marti_state_estimator imu_processing README.md gps_processing velocity_aggregation Localization Data Flow.png marti_localization_msgs localization_util localization_calibration_tools wheel_encoder_processing nmea_writer' returned non-zero exit status 128

Error calling generator post_rebase: Command 'git rm -rf marti_state_estimator imu_processing README.md gps_processing velocity_aggregation Localization Data Flow.png marti_localization_msgs localization_util localization_calibration_tools wheel_encoder_processing nmea_writer' returned non-zero exit status 128
generator post_rebase returned exit code (128)
```

**Comment by nuclearsandwich** [comment]
Thanks for the report @pjreed. If you have the opportunity to submit a pull request addressing this issue, or even adding a failing test case, you would be welcome to do so.
