### ISSUE TITLE
python module "requests" missing after fresh install of bloom

### ISSUE THREAD

**Issue by rhaschke** [ros-infrastructure/bloom#467]
The ubuntu package `python-bloom` obviously misses a dependency to `python-requests`. After manually installing the latter package, the following error is gone:

```bash
bloom-release --rosdistro kinetic --track kinetic agni_tf_tools --edit
Traceback (most recent call last):
  File "/usr/bin/bloom-release", line 9, in <module>
    load_entry_point('bloom==0.6.3', 'console_scripts', 'bloom-release')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 47, in <module>
    import requests
ImportError: No module named requests
```

**Comment by nuclearsandwich** [comment]
This was introduced in https://github.com/ros-infrastructure/bloom/pull/460 and I forgot to comment on it. We should replace the requests usage with standard library functions.

**Comment by nuclearsandwich** [comment]
Version 0.6.4 which fixes this issue has been released via the ROS apt repositories and pip. Thanks for reporting it!
