### ISSUE TITLE
test_catkin_release failing

### ISSUE THREAD

**Issue by kyrofa** [ros-infrastructure/bloom#616]
Getting this failure consistently; I see it in the most recent PRs as well. 

```
======================================================================
FAIL: Release a multi package catkin (melodic) repository.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/esm/ros-common/ros-infrastructure/bloom/test/utils/common.py", line 136, in decorated
    return f(*args, **kwds)
  File "/home/ubuntu/esm/ros-common/ros-infrastructure/bloom/test/system_tests/test_catkin_release.py", line 326, in test_multi_package_repository
    "no debian/melodic/" + pkg + " branch"
AssertionError: no debian/melodic/foo branch

----------------------------------------------------------------------
Ran 1 test in 43.838s

FAILED (failures=1)
```

@cottsay beyond https://github.com/ros-infrastructure/bloom/pull/614 looking like a generally good idea on its own, it also seems to fix this issue. What exactly broke, though?

**Comment by kyrofa** [comment]
Oh you explicitly call it out in the PR: https://github.com/ros/rosdistro/pull/27640. I'm sorry.
