### ISSUE TITLE
PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release

### ISSUE THREAD

**Issue by ijnek** [ros-infrastructure/bloom#678]
Following warning spams when running ``bloom-release``:

```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
```

This deprecation warning was [added to pypa/setuptools](https://github.com/pypa/setuptools/commit/84b1cd8e7760a9b3c984a4edfc37dc7266952266) some time last year, and it seems like all the has to be done is to use ``packaging.parse`` instead of ``pkg_resources.parse_version`` as described in [PEP 440](https://peps.python.org/pep-0440/).

I will try and get a fix in if no one gets to it first.

**Comment by jbarry-bdai** [comment]
With setuptools 66.0.0 this now breaks `bloom-generate` on anything but Mac I believe:
```
Traceback (most recent call last):
  File "/usr/local/bin/bloom-generate", line 5, in <module>
    from bloom.commands.generate import main
  File "/usr/local/lib/python3.10/dist-packages/bloom/commands/__init__.py", line 42, in <module>
    from bloom.commands.update import start_updater
  File "/usr/local/lib/python3.10/dist-packages/bloom/commands/update.py", line 49, in <module>
    from bloom.logging import warning
  File "/usr/local/lib/python3.10/dist-packages/bloom/logging.py", line 63, in <module>
    _is_mac_lion_or_greater = parse_version(mac_ver()[0]) >= parse_version('10.7.0')
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: ''
```
 Downgrading setuptools to 65.7.0 solved the problem.

**Comment by facontidavide** [comment]
Thanks, I had this same problem. Is there any solution? I think many people might be affected!
