### ISSUE TITLE
Cannot Release for Humble on Ubuntu 18.04

### ISSUE THREAD

**Issue by danthony06** [ros-infrastructure/bloom#692]
I'm running 18.04 and just tried releasing a package for Humble with bloom from both the Ubuntu repositories and pip. In both cases, I get the following error message:

```
bloom-release --edit --rosdistro humble --track humble marti_common
Traceback (most recent call last):
  File "/usr/local/bin/bloom-release", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/bloom/commands/release.py", line 1217, in main
    args.override_release_repository_push_url)
  File "/usr/local/lib/python3.6/dist-packages/bloom/commands/release.py", line 1055, in perform_release
    release_repo = get_release_repo(repository, distro, override_release_repository_url)
  File "/usr/local/lib/python3.6/dist-packages/bloom/commands/release.py", line 284, in get_release_repo
    url = get_repo_uri(repository, distro)
  File "/usr/local/lib/python3.6/dist-packages/bloom/commands/release.py", line 225, in get_repo_uri
    distribution_file = get_distribution_file(distro)
  File "/usr/local/lib/python3.6/dist-packages/bloom/rosdistro_api.py", line 173, in get_distribution_file
    files = rosdistro.get_distribution_files(get_index(), distro)
  File "/usr/lib/python3/dist-packages/rosdistro/__init__.py", line 124, in get_distribution_files
    data = _get_dist_file_data(index, dist_name, 'distribution')
  File "/usr/lib/python3/dist-packages/rosdistro/__init__.py", line 186, in _get_dist_file_data
    raise RuntimeError("Unknown release: '{0}'. Valid release names are: {1}".format(dist_name, ', '.join(sorted(index.distributions.keys()))))
RuntimeError: Unknown release: 'humble'. Valid release names are: ardent, bouncy, crystal, dashing, eloquent, foxy, galactic, groovy, hydro, indigo, jade, kinetic, lunar, melodic, noetic, rolling
```

**Comment by cottsay** [comment]
Are you using the `ROSDISTRO_INDEX_URL` environment variable to pin the rosdistro state to an older version of the ros/rosdistro repository?

This command should show what the index URL is being set to:
```
$ python3 -c "import rosdistro; print(rosdistro.get_index_url())"
https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
```

**Comment by danthony06** [comment]
Okay, thanks, that revealed the problem. It's on my end.
