### ISSUE TITLE
CI failing on master

### ISSUE THREAD

**Issue by nuclearsandwich** [ros-infrastructure/bloom#696]
An apparent change in behavior in the deprecated `pkg_resources.parse_version` function is causing CI to regress on master.

#693 replaces this function (and in particular removes the use of it where the version could be an empty string) and resolves the issue.

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/work/bloom/bloom/test/unit_tests/test_generators/test_debian/test_generator.py", line 5, in <module>
    from bloom.generators.debian.generator import em
  File "/home/runner/work/bloom/bloom/bloom/generators/__init__.py", line 35, in <module>
    from .common import BloomGenerator
  File "/home/runner/work/bloom/bloom/bloom/generators/common.py", line 39, in <module>
    from bloom.logging import debug
  File "/home/runner/work/bloom/bloom/bloom/logging.py", line 63, in <module>
    _is_mac_lion_or_greater = parse_version(mac_ver()[0]) >= parse_version('10.7.0')
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: ''
```

**Comment by nuclearsandwich** [comment]
In order to keep better track of regressions in the future I've opened https://github.com/ros-infrastructure/bloom/pull/695

**Comment by tylerjw** [comment]
Here is a link to my ros-answers question about this: https://answers.ros.org/question/414747/bloom-error-about-invalid-version/

It would be nice to get a release of bloom that includes this fix.

**Comment by tfoote** [comment]
I just setup a new machine and I'm running into this error.
